# adapted from https://github.com/XYQuadrat/eth-cheatsheets

name: Build LaTeX documents

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v2
      
        with:
          fetch-depth: 0
      - name: Fetch tags
        shell: bash
        run: git fetch --tags -f
      - name: Install XeLaTeX
        shell: bash
        run: sudo apt-get install -y latexmk texlive-xetex texlive-science texlive-lang-german texlive-lang-chinese
      - name: Build LaTeX documents
        shell: bash
        run: |
          mkdir $GITHUB_WORKSPACE/latex-output
          find . -name '*.tex' \( -exec latexmk -synctex=1 -xelatex -interaction=nonstopmode -outdir=$GITHUB_WORKSPACE/latex-output -cd "$PWD"/{} \; -o -print \)
      - name: Deploy
        if: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="nightly"
          git tag -f "$TAG"
          hub release delete "$TAG"
          hub release create -m "Nightly PDF build
          
          This release always contains the PDFs built from the latest .tex source. It is advised to only use the latest versions for actual exams, as old versions might contain factual errors." "$TAG" || true
          for file in $GITHUB_WORKSPACE/latex-output/*.pdf; do
            echo "Delivering file $file"
            gh release upload "$TAG" "$file" --clobber
          done
